version: '3'
services:
  mysql:
        image: mysql:8.0
        container_name: mysql-server-80
        command: --default-authentication-plugin=mysql_native_password
#        working_dir: /application
        volumes:
          - .:/var/lib/mysql/data
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=.sweetpwd.
          - MYSQL_DATABASE=my_db
          - MYSQL_USER=db_user
          - MYSQL_PASSWORD=.mypwd
        ports:
          - "8082:3306"
  website:
    container_name: php72
    image: phpmysql
    build:
      context: ./
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8080:80
    depends_on:
      - mysql
