apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: website
  name: website
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: phpmysql
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
